# Generated by Django 3.1.5 on 2021-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_trigger', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=10)),
                ('reuse', models.BooleanField(default=False)),
                ('pick_first', models.BooleanField(default=False)),
                ('support_multiple', models.BooleanField(default=False)),
                ('validation_parser', models.CharField(max_length=30)),
                ('constraint', models.CharField(max_length=20)),
                ('var_name', models.CharField(max_length=10)),
            ],
        ),
    ]
