# Generated by Django 3.1.5 on 2021-01-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedValuesArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TagArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ValuesArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_trigger', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=10)),
                ('reuse', models.BooleanField()),
                ('support_multiple', models.BooleanField()),
                ('pick_first', models.BooleanField()),
                ('validation_parser', models.CharField(max_length=20)),
                ('supported_values', models.ManyToManyField(to='documents.SupportedValuesArray')),
                ('type', models.ManyToManyField(to='documents.TagArray')),
                ('values', models.ManyToManyField(to='documents.ValuesArray')),
            ],
        ),
    ]
