# Generated by Django 3.1.5 on 2021-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='supported_values',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='values',
        ),
        migrations.AlterField(
            model_name='document',
            name='pick_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='reuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='support_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='validation_parser',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='SupportedValuesArray',
        ),
        migrations.DeleteModel(
            name='TagArray',
        ),
        migrations.DeleteModel(
            name='ValuesArray',
        ),
    ]
